// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMBjLEhU-DB70yF_z0G6WEMimv4q6VNxM',
    appId: '1:937276144508:web:0f886d87a4f015e791c2f9',
    messagingSenderId: '937276144508',
    projectId: 'flagsquiz-a78b8',
    authDomain: 'flagsquiz-a78b8.firebaseapp.com',
    storageBucket: 'flagsquiz-a78b8.firebasestorage.app',
    measurementId: 'G-L1F7GFKZTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXIjO9v_mhiQnXthS-iw7XsQn_ZOq5wYw',
    appId: '1:937276144508:android:d33afdadfb15217d91c2f9',
    messagingSenderId: '937276144508',
    projectId: 'flagsquiz-a78b8',
    storageBucket: 'flagsquiz-a78b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp9UWM8kenVncxwx9MKNkndl-xpiGBl_c',
    appId: '1:937276144508:ios:ebf99e03142f438591c2f9',
    messagingSenderId: '937276144508',
    projectId: 'flagsquiz-a78b8',
    storageBucket: 'flagsquiz-a78b8.firebasestorage.app',
    iosBundleId: 'com.volodymyrs.flagsquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp9UWM8kenVncxwx9MKNkndl-xpiGBl_c',
    appId: '1:937276144508:ios:ebf99e03142f438591c2f9',
    messagingSenderId: '937276144508',
    projectId: 'flagsquiz-a78b8',
    storageBucket: 'flagsquiz-a78b8.firebasestorage.app',
    iosBundleId: 'com.volodymyrs.flagsquiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMBjLEhU-DB70yF_z0G6WEMimv4q6VNxM',
    appId: '1:937276144508:web:0e3fcfcfcf4d7c1e91c2f9',
    messagingSenderId: '937276144508',
    projectId: 'flagsquiz-a78b8',
    authDomain: 'flagsquiz-a78b8.firebaseapp.com',
    storageBucket: 'flagsquiz-a78b8.firebasestorage.app',
    measurementId: 'G-9CGG0TLHC3',
  );
}
